
#ifndef CONFIG_H
#define CONFIG_H

#define SEGMENT_LENGTH 100.0
#define HIGHWAY_SEGMENT_LENGTH 200.0
#define HIGHWAY_SEGMENT_WIDTH 20.0
#define DEFAULT_SEGMENT_WIDTH 10.0
#define HIGHWAY_CAPACITY 12
#define DEFAULT_CAPACITY 6
#define HIGHWAY_SPEED 1200.0
#define DEFAULT_SPEED 800.0
#define SEGMENT_COUNT_LIMIT 1000
#define SNAP_DISTANCE 15.0
#define MIN_INTERSECTION_DEVIATION 15.0

#endif
